Feat/get paginated organizations
vtex-apps/storefront-permissions pull request #172
Opened 2024-11-27 17:39 UTC by guidobernal-cubos

**What problem is this solving?**

This update optimizes the retrieval of organizations and cost center information by implementing paginated queries instead of fetching all data at once. It prevents timeouts and improves performance when users are associated with a large number of organizations.

ClickUp: https://app.clickup.com/t/868amdqqw

**How should this be manually tested?**

1. Test with an email associated with a small number of organizations to ensure correct data retrieval.
2. Test with an email linked to a large number of organizations to verify that pagination works correctly and avoids timeouts.
3. Confirm that:
   - A valid `costId` is returned if a cost center is available.
   - An organization with a status other than `inactive` is retrieved correctly.
   - Proper null responses occur when no valid data is found.
4. Use edge cases, such as emails with no associated organizations, to confirm behavior. 

**Screenshots or example usage:**

![image](https://github.com/user-attachments/assets/04d6001b-09f3-4e8c-82c7-50b0774748fb)

`{
  getOrganizationsPaginatedByEmail(email: "", page: 1, pageSize: 25) {
    data {
      id
      clId
      costId
      orgId
    }
    pagination {
      page
      pageSize
      total
    }
  }
}
`

b2b-organizations-graphql PR: https://github.com/vtex-apps/b2b-organizations-graphql/pull/189

2024-11-27 18:44 UTC, tiago-freire requested changes

2024-11-27 18:44 UTC, tiago-freire commented on node/resolvers/Routes/utils/index.ts
> +};
Eu faria 2 mudanças aqui:

- colocar o parâmetro opcional `pageSize` por último. Assim, vc poderia alterar a linha 277 de node/resolvers/Routes/index.ts:
  de
  ```typescript
  const costId = await getCostIdFromOrganizationWithValidCostCenter(email, 50, ctx);
  ```
  para
  ```typescript
  const costId = await getCostIdFromOrganizationWithValidCostCenter(email, ctx);
  ```

- talvez ficasse mais elegante usar recursão no lugar desse `while (true)`.

Exemplo de implementação com parâmetros opcionais por último e utilizando recursão:

```typescript
export const getCostIdFromOrganizationWithValidCostCenter = async (
  email: string,
  ctx: Context,
  page: number = 1, // novo parâmetro page (opcional) para usar na recursão
  pageSize: number = 50 // os dois parâmetros opcionais page e pageSize por último
): Promise<string | null> => {
  const { organizations } = ctx.clients;
  const response = await organizations.getOrganizationsPaginatedByEmail(email, page, pageSize);
  const { data, pagination } = response?.data?.getOrganizationsPaginatedByEmail || {};

  if (!data?.length) {
    return null;
  }

  const organization = data.find(org => org.costCenterName !== null);

  if (organization) {
    return organization.costId;
  }

  const totalPages = Math.ceil((pagination?.total || 0) / pageSize);

  if (page >= totalPages) {
    return null;
  }

  return getCostIdFromOrganizationWithValidCostCenter(email, ctx, page + 1, pageSize);
};
```

2024-12-04 17:13 UTC, tiago-freire requested changes

2024-12-04 17:13 UTC, tiago-freire commented on node/resolvers/Queries/Users.ts
> +    const responses = await Promise.all(requests)
Imagine que pode haver milhares de páginas. Acho que pode ser perigoso rodar em paralelo todos os requests sem uma limitação. Testa por favor mudar essa linha 91 para esse trecho:

```js
const responses = []
const maxConcurrency = 10

while (true) {
  if (!requests.length) break

  const response = await Promise.all(requests.splice(0, maxConcurrency))

  if (response?.length) responses.push(...response)
}
```

A função [splice](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) é tipo a slice (extrai um pedaço do array), mas que vai diminuindo o tamanho do array a cada vez que é chamada, até não ter mais elementos.

2024-12-04 17:15 UTC, tiago-freire commented on node/resolvers/Queries/Users.ts
> +    const responses = await Promise.all(requests)
Caso funcione dessa forma, podemos testar valores maiores no `maxConcurrency` até chegar a um ponto que seja eficiente e ao mesmo tempo não comprometa a aplicação.

2025-09-04 17:40 UTC, enzomerca commented on node/resolvers/Routes/utils/index.ts
> +    const response = await organizations.getOrganizationsPaginatedByEmail(email, page, pageSize);
Precisamos chamar o `getOrganizationsPaginatedByEmail` la do `b2b-organizations-graphql`? Pelo que eu vi ele só chama o `getOrganizationsPaginatedByEmail` aqui do `storefront-permissions` e retorna. Será que não podemos chamar o do `storefront-permissions` direto? assim evitamos 2 hops entre aplicações desnecessários.

Dessa forma nem precisamos desse [PR](https://github.com/vtex-apps/b2b-organizations-graphql/pull/189/files) no `b2b-organizations-graphql` também.

2025-09-05 12:34 UTC, giurigaud commented on node/resolvers/Routes/utils/index.ts
> +    const response = await organizations.getOrganizationsPaginatedByEmail(email, page, pageSize);
acho que faz sentido sim. acredito que ele tenha feito dessa forma para seguir o padrão que já existia dos dados das orgs virem sempre da b2b-organizations-graphql, mas eu concordo em fazer como vc disse, vou fechar a PR.

2025-09-15 13:15 UTC, enzomerca commented on node/resolvers/Queries/Users.ts
> +export const getOrganizationsPaginatedByEmail = async (
@giurigaud  Dada a sua resposta no outro comentário, será que não conseguimos levar essa implementação então para o `b2b-organizations-graphql`? assim o `b2b-organizations-graphql` não precisa chamar o `storefront-permissions` de volta?

2025-10-09 14:50 UTC, merged